version: '3.7'

services:

  db:
    image: mysql:5.7
    container_name: app-mysql
    restart: always
    ports:
      - 8080:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql/dumps:/docker-entrypoint-initdb.d
    networks:
      - laravelapp

  nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - laravelapp

  laravel:
    build:
      args:
        user: laraveluser
        uid: 1000
      context: ./docker/php/
      dockerfile: Dockerfile
    image: laravel
    container_name: app-laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravelapp

networks:
  laravelapp:
    driver: bridge
